export default [
  // sneaker sizing chart
  { key: '3.5_SHOE', text: '3.5', value: '3.5_S' },
  { key: '4_SHOE', text: '4', value: '4_S' },
  { key: '4.5_SHOE', text: '4.5', value: '4.5_S' },
  { key: '5_SHOE', text: '5', value: '5_S' },
  { key: '5.5_SHOE', text: '5.5', value: '5.5_S' },
  { key: '6_SHOE', text: '6', value: '6_S' },
  { key: '6.5_SHOE', text: '6.5', value: '6.5_S' },
  { key: '7_SHOE', text: '7', value: '7_S' },
  { key: '7.5_SHOE', text: '7.5', value: '7.5_S' },
  { key: '8_SHOE', text: '8', value: '8_S' },
  { key: '8.5_SHOE', text: '8.5', value: '8.5_S' },
  { key: '9_SHOE', text: '9', value: '9_S' },
  { key: '9.5_SHOE', text: '9.5', value: '9.5_S' },
  { key: '10_SHOE', text: '10', value: '10_S' },
  { key: '10.5_SHOE', text: '10.5', value: '10.5_S' },
  { key: '11_SHOE', text: '11', value: '11_S' },
  { key: '11.5_SHOE', text: '11.5', value: '11.5_S' },
  { key: '12_SHOE', text: '12', value: '12_S' },
  { key: '12.5_SHOE', text: '12.5', value: '12.5_S' },
  { key: '13_SHOE', text: '13', value: '13_S' },
  { key: '14_SHOE', text: '14', value: '14_S' },
  { key: '15_SHOE', text: '15', value: '15_S' },
  { key: '16_SHOE', text: '16', value: '16_S' },
  { key: '17_SHOE', text: '17', value: '17_S' },
  { key: '18_SHOE', text: '18', value: '18_S' },
  // apparel sizing chart
  { key: 'XXS_APPAREL', text: 'XXS', value: 'XXS_A' },
  { key: 'XS_APPAREL', text: 'XS', value: 'XS_A' },
  { key: 'S_APPAREL', text: 'S', value: 'S_A' },
  { key: 'M_APPAREL', text: 'M', value: 'M_A' },
  { key: 'L_APPAREL', text: 'L', value: 'L_A' },
  { key: 'XL_APPAREL', text: 'XL', value: 'XL_A' },
  { key: 'XXL_APPAREL', text: 'XXL', value: 'XXL_A' },
  { key: '3XL_APPAREL', text: '3XL', value: '3XL_A' },
  // misc
  { key: 'OS_MISC', text: 'OS', value: 'OS_M' },
];
